// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/OrangePortraitEventPoster-TH76mR/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-TH76mR/DeepOrangePoster.tsx"),
  "./components/mockups/templates/OrangePortraitEventPoster-w781CX/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-w781CX/DeepOrangePoster.tsx")
};
